config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("recipegram_fullstack.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Recipe management
    path("", include("recipes.urls", namespace="recipes")),
    path("favorites/", include("favorites.urls", namespace="favorites")),
    path("shopping/", include("shopping.urls", namespace="shopping")),
    path("follows/", include("follows.urls", namespace="follows")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

recipegram_fullstack/follows/urls.py
from django.urls import path

from . import views

app_name = "follows"

urlpatterns = [
    path("follow/<str:username>/", views.follow, name="follow"),
    path("unfollow/<str:username>/", views.unfollow, name="unfollow"),
    path("followers/", views.followers, name="followers"),
    path("following/", views.following, name="following"),
    path("recipes/<str:username>/", views.user_recipes, name="user_recipes"),
]

recipegram_fullstack/recipes/urls.py
from django.urls import path

from . import views

app_name = "recipes"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<uuid:recipe_id>/", views.detail, name="detail"),
    path("<uuid:recipe_id>/edit/", views.edit, name="edit"),
    path("<uuid:recipe_id>/delete/", views.delete, name="delete"),
]

recipegram_fullstack/shopping/urls.py
from django.urls import path

from . import views

app_name = "shopping"

urlpatterns = [
    path("list/", views.shopping_list, name="list"),
    path("add/<uuid:recipe_id>/", views.add_to_shopping_list, name="add"),
    path("remove/<uuid:recipe_id>/", views.remove_from_shopping_list, name="remove"),
    path("download/", views.download_shopping_list, name="download"),
]

recipegram_fullstack/users/urls.py
from django.urls import path

from recipegram_fullstack.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

recipegram_fullstack/favorites/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Favorite(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    recipe = models.ForeignKey("recipes.Recipe", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="favorites")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("user", "recipe")

    def __str__(self):
        return str(self.recipe)

recipegram_fullstack/follows/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Follow(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    follower = models.ForeignKey(
        User, related_name="following_set", on_delete=models.CASCADE
    )
    following = models.ForeignKey(
        User, related_name="follower_set", on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("follower", "following")

    def __str__(self):
        return f"{self.follower.username} follows {self.following.username}"

recipegram_fullstack/recipes/forms.py
from django import forms

from .models import MEAL_TYPE_CHOICES, TAGS_CHOICES, Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = [
            "title",
            "description",
            "image",
            "tags",
            "meal_type",
            "ingredients",
            "instructions",
            "servings",
            "prep_time_in_minutes",
            "cook_time_in_minutes",
            "total_time",
        ]

    title = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    description = forms.CharField(
        widget=forms.Textarea(attrs={"class": "form-control"})
    )
    image = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={"class": "form-control"})
    )
    tags = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple, choices=TAGS_CHOICES
    )
    meal_type = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple, choices=MEAL_TYPE_CHOICES
    )
    ingredients = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    instructions = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    servings = forms.IntegerField(
        widget=forms.NumberInput(attrs={"class": "form-control"})
    )
    prep_time_in_minutes = forms.IntegerField(
        widget=forms.NumberInput(attrs={"class": "form-control"})
    )
    cook_time_in_minutes = forms.IntegerField(
        widget=forms.NumberInput(attrs={"class": "form-control"})
    )
    total_time = forms.IntegerField(
        widget=forms.NumberInput(attrs={"class": "form-control"})
    )

    def clean_ingredients(self):
        if ingredients := self.cleaned_data.get("ingredients"):
            return ingredients.split(",")
        else:
            raise forms.ValidationError("Please enter ingredients for the recipe")

    def clean_instructions(self):
        if instructions := self.cleaned_data.get("instructions"):
            return instructions.split(",")
        else:
            raise forms.ValidationError("Please enter instructions for the recipe")

recipegram_fullstack/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

recipegram_fullstack/favorites/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from recipes.models import Recipe

from .models import Favorite

User = get_user_model()


def favorites_list(request):
    favorites = Favorite.objects.all().order_by("-created_at")
    paginator = Paginator(favorites, 6)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "favorites/index.html", {"page_obj": page_obj})


@login_required
def add_to_favorites(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    created = Favorite.objects.get_or_create(user=request.user, recipe=recipe)
    if created:
        message = "Recipe added to favorites!"
    else:
        message = "Recipe already in favorites."
    data = {"message": message}
    return JsonResponse(data)


@login_required
def remove_from_favorites(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    Favorite.objects.filter(user=request.user, recipe=recipe).delete()
    message = "Recipe removed from favorites!"
    data = {"message": message}
    return JsonResponse(data)

recipegram_fullstack/follows/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from recipes.models import Recipe

from .models import Follow

User = get_user_model()


@login_required
def follow(request, username):
    user = get_object_or_404(User, username=username)
    follow, created = Follow.objects.get_or_create(
        follower=request.user, following=user
    )
    if created:
        message = f"You are now following {user.username}"
    else:
        message = f"You are already following {user.username}"
    data = {"message": message}
    return JsonResponse(data)


@login_required
def unfollow(request, username):
    user = get_object_or_404(User, username=username)
    Follow.objects.filter(follower=request.user, following=user).delete()
    message = f"You are no longer following {user.username}"
    data = {"message": message}
    return JsonResponse(data)


@login_required
def followers(request):
    followers = Follow.objects.filter(following=request.user).order_by("-created_at")
    paginator = Paginator(followers, 6)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "follows/followers.html", {"page_obj": page_obj})


@login_required
def following(request):
    following = Follow.objects.filter(follower=request.user).order_by("-created_at")
    paginator = Paginator(following, 6)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "follows/following.html", {"page_obj": page_obj})


@login_required
def user_recipes(request, username):
    user = get_object_or_404(User, username=username)
    recipes = Recipe.objects.filter(author=user).order_by("-created_at")
    paginator = Paginator(recipes, 6)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(
        request, "follows/user_recipes.html", {"user": user, "page_obj": page_obj}
    )

recipegram_fullstack/recipes/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.cache import cache_page
from django.views.decorators.http import require_POST

from .forms import RecipeForm
from .models import Recipe

User = get_user_model()


# @cache_page(60 * 10)
def index(request):
    recipes = Recipe.objects.all().order_by("-created_at")
    paginator = Paginator(recipes, 12)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {"page_obj": page_obj}
    return render(request, "recipes/index.html", context)


@login_required
@cache_page(60 * 10)
def create(request):
    form = RecipeForm(request.POST, request.FILES)
    if request.method == "POST":
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()
            form.save_m2m()
            messages.success(request, "Recipe created successfully!")
            return render(request, "recipes/create.html", {"form": RecipeForm()})
        return JsonResponse({"errors": form.errors}, status=400)
    return render(request, "recipes/create.html", {"form": form})


def detail(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    return render(request, "recipes/detail.html", {"recipe": recipe})


@login_required
def edit(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    form = RecipeForm(request.POST, request.FILES, instance=recipe)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, "Recipe updated successfully!")
            return render(request, "recipes/edit.html", {"form": form})
        return JsonResponse({"errors": form.errors}, status=400)
    context = {"form": form}
    return render(request, "recipes/edit.html", context)


@login_required
@require_POST
def delete(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    recipe.delete()
    return JsonResponse({"deleted": True})

recipegram_fullstack/shopping/views.py
import csv

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render
from recipes.models import Recipe

from .models import ShoppingList


@login_required
def add_to_shopping_list(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    ShoppingList.objects.get_or_create(user=request.user, recipe=recipe)
    message = "Recipe added to shopping list!"
    return JsonResponse({"message": message})


@login_required
def remove_from_shopping_list(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    ShoppingList.objects.filter(user=request.user, recipe=recipe).delete()
    message = "Recipe removed from shopping list!"
    data = {"message": message}
    return JsonResponse(data)


@login_required
def shopping_list(request):
    shopping_list = ShoppingList.objects.filter(user=request.user).order_by(
        "-created_at"
    )
    paginator = Paginator(shopping_list, 6)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "shopping/index.html", {"page_obj": page_obj})


@login_required
def download_shopping_list(request):
    user = request.user
    shopping_list = ShoppingList.objects.filter(user=user)
    response = HttpResponse(content_type="text/csv")
    response["Content-Disposition"] = 'attachment; filename="shopping_list.csv"'
    writer = csv.writer(response)
    writer.writerow(["Title", "Ingredients", "Created at"])
    for item in shopping_list:
        writer.writerow([item.recipe.title, item.recipe.ingredients, item.created_at])

    return response

recipegram_fullstack/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

recipegram_fullstack/templates/follows/following.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1 class="display-6  mb-4">Subsriptions</h1>
  {% for follows in page_obj%}
  <div class="row">
    <div class="col-md-6 details">
      <blockquote>
        <h5>{{follows.following.username}}</h5>
        <small><cite title="Source Title">
          Im a food lover and I love to cook. I like to share my recipes, mainly desserts, but I also like to share main dishes and appetizers. <br>
          <i class="icon-map-marker"></i></cite></small>
      </blockquote>
      <p>
        {{ follows.following.bio }}
      </p>
    </div>
  </div>
  <div class="row mb-5">
    <div class="col-12 col-sm-4">
      <div class="card emphasis">
          <div class="card-body text-center">
              <h2 class="card-title"><strong>
                {{follows.following.followers.all|length}}
              </strong></h2>
              <p class="card-text"><small>Followers</small></p>
              {% if follows.following.username in following %}
                <a href="{% url "follows:unfollow" follows.following.username %}" class="btn btn-outline-success btn-block"><span class="bi bi-person-plus"></span> Follow</a>
              {% else %}
                <a href="{% url "follows:follow" follows.following.username %}" class="btn btn-outline-success btn-block"><span class="bi bi-person-plus"></span> Follow</a>
              {% endif %}
              </div>
      </div>
  </div>
  <div class="col-12 col-sm-4">
      <div class="card emphasis">
          <div class="card-body text-center">
              <h2 class="card-title"><strong>
                {{follows.following.following.all|length}}
              </strong></h2>
              <p class="card-text"><small>Following</small></p>
              <button class="btn btn-outline-info btn-block"><span class="bi bi-person-check"></span> Following</button>
          </div>
      </div>
  </div>
  <div class="col-12 col-sm-4">
    <div class="card emphasis">
        <div class="card-body text-center">
            <h2 class="card-title"><strong>
              {{follows.following.recipes.all|length}}
            </strong></h2>
            <p class="card-text"><small>Recipes</small></p>
            <a href="{% url "follows:user_recipes" follows.following.username %}" class="btn btn-outline-primary btn-block">View Recipe</a>
        </div>
    </div>
  </div>
</div>
  {% endfor %}
</div>
{% endblock content %}

recipegram_fullstack/templates/follows/user_recipes.html
{% extends "base.html" %}

{% block content %}
<div class="container">

  {% comment %} author details row {% endcomment %}
  <div class="row">
    <div class="col-md-6">
      <img src="https://via.placeholder.com/200/" alt="" class="rounded-circle float-start me-3 profile-img">
      <h5 class="profile-name">{{ user.username }}</h5>
      <p class="profile-email">{{ user.email }}</p>
      <p class="profile-bio">I'm a food lover and I love to cook</p>
      {% if user in following %}
        <a href="{% url 'follows:unfollow' user.username %}" class="btn btn-danger btn-sm"><i class="bi bi-person-fill-dash"></i> Unfollow</a>
      {% else %}
        <a href="{% url 'follows:follow' user.username %}" class="btn btn-success btn-sm"><i class="bi bi-person-fill-add"></i> Follow</a>
      {% endif %}
    </div>
  </div>

  {% comment %} Row display list of recipes {% endcomment %}
  <div class="row my-5">
    {% for recipe in page_obj %}
    <div class="col-lg-4 pb-4" id="recipe-card">
        <div class="card h-100 recipe-card">
          <a href=""><img class="card-img-top recipe-img" src="{{ recipe.image.url }}" alt="{{recipe.title}}"></a>
          <div class="card-body">
            <h5 class="card-title"><a class="recipe-title" href="{% url "recipes:detail" recipe.id %}">{{ recipe.title }} </a></h5>
            <p class="card-text"></p>
            <p class="card-text">
              <i class="bi bi-person"></i>
              <span class="recipe-author"><a href="{% url "follows:user_recipes" recipe.author %}" class="text-secondary" style="text-decoration:none">{{recipe.author}}</a></span>
            </p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <form id="add-to-cart-form" action="{% url 'shopping:add' recipe.id %}" method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="recipe_id" value="{{ recipe.id }}">
                  <button class="btn btn-sm btn-outline-success add" onclick="addToShoppingList(event)">Add to Cart</button>
                </form>
              </div>
              <div class="btn-group">
                <form action="{% url 'recipes:detail' recipe.id %}" method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="recipe_id" value="{{ recipe.id }}">
                  <button href="{% url 'favorites:remove' recipe.id %}" class="btn btn-sm favorite-btn"><i class="bi bi-heart-fill"></i></button>
                </form>
              </div>
            </div>
          </div>
          <div class="card-footer text-muted text-truncate">
            {% for tag in recipe.tags %}
              <span class="badge rounded-pill recipe-badge">
                <a href="" class="text-decoration-none text-white">#{{ tag }}</a>
              </span>
            {% endfor %}
          </div>
        </div>
    </div>
    {% endfor %}
  </div>

  {% comment %} Row display pagination links {% endcomment %}
  <div class="row m-3">
    <div class="col">
        <div class="d-flex justify-content-center">
          <nav aria-label="Page navigation example">
            <ul class="pagination">
              {% if page_obj.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="?page=1" aria-label="First">
                    <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&lt;</span>
                  </a>
                </li>
              {% endif %}
              {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                  <li class="page-item active">
                    <a class="page-link" href="#">{{ num }} <span class="sr-only">(current)</span></a>
                  </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                  </li>
                {% endif %}
              {% endfor %}
              {% if page_obj.has_next %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&gt;</span>
                  </a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                    <span aria-hidden="true">&raquo;</span>
                  </a>
                </li>
              {% endif %}
            </ul>
          </nav>
        </div>
    </div>
</div>
{% endblock content %}